### ISSUE TITLE
Remove colours

### ISSUE THREAD

**Issue by PaoloUccello** [HartBlanc/anki-uk-geography#4]
I think one should be required to remember the counties based on shape and position without the help of an arbitrary colour. What do people think?

**Comment by HartBlanc** [comment]
I agree! I'm actually already working on a version where I've  removed all the colours. The new version without the arbitrary colours (and quite a few other changes) will be coming in the next week or so.

**Comment by PaoloUccello** [comment]
I think typing boxes would also be an improvement when one's asked to name something.

```js
<script>
  document.getElementById('typeans').style.fontSize = '60px';
</script>
```

This can be used to change the size of the boxes.

**Comment by HartBlanc** [comment]
Thanks for the suggestion! Will add a typing option to the next version too.

**Comment by HartBlanc** [comment]
Hey, this is implemented in the latest release, you can pick It up in the releases tab or on ankiweb as usual.
